### ISSUE TITLE
Win64 build failed because it cannot open include file: 'CppCoreCheck\Warnings.h'

### ISSUE THREAD

**Issue by myd7349** [simdjson/simdjson#880]
**Describe the bug**

Hi! I was trying to update `vcpkg`'s simdjson to lastest recently(https://github.com/microsoft/vcpkg/pull/10709), and found that `vcpkg`'s CI complains that it failed on `x64-windows` and `arm64-windows` because it can not find 'CppCoreCheck\Warnings.h'. The build log can be downloaded from here: https://dev.azure.com/vcpkg/public/_build/results?buildId=36632&view=artifacts&type=publishedArtifacts

> C:\agent\_work\1\s\buildtrees\simdjson\src\f2f38aa02a-04d62f41b8\include\simdjson/common_defs.h(80): fatal error C1083: Cannot open include file: 'CppCoreCheck\Warnings.h': No such file or directory

I have also tried to install `simdjson` on my own Win10 x64 PC with VS2017, and encountered the same issue. But when I searched on my machine, I can find this header file under: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\include\CppCoreCheck.

Note: On some other CI machine(https://github.com/myd7349/simdjson-cmake-example/runs/651753294), though, everything seems ok.

I am not quite familiar with MSVC's CoreGuideline Check, does it need some additionl configuration to make things work out?

**To Reproduce**
Not sure how to reproduce it.

**Configuration (please complete the following information if relevant):**
 - OS: Win10 x64
 - Compiler: MSVC
 - Version:

**Comment by lemire** [comment]
This is strange since the header seems normally available. But not always.

I have created a PR:

https://github.com/simdjson/simdjson/pull/881

**Comment by lemire** [comment]
@myd7349 Hopefully this particular bug is fixed. I have guarded the include.

**Comment by myd7349** [comment]
Hi! @lemire Sorry for the delay.
But it seems that the single header/source version should also be updated. Otherwise, the error still exists.

**Comment by lemire** [comment]
@myd7349 The single-header will get updated soon given that @jkeiser has some PRs that are ready to be merge that do so. I bet that this will be resolved in a day or so.
